### PR TITLE
Use the same HTTP protocol for the redirect

### PR DESCRIPTION
**Pull request by MorrisJobke**
See change in the README.md

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Background:

The federation ID never contains the protocol:

https://github.com/nextcloud/server/blob/a8bb4a18988534323d872b13a9895a2c9557b6c5/apps/lookup_server_connector/lib/UpdateLookupServer.php#L96
https://github.com/nextcloud/server/blob/999455c1aa8fc4a02a2fd778cd25fe3e4a1843ac/lib/private/User/User.php#L435

**Comment by MorrisJobke** [comment]
Even that the code uses `resolveCloudId()` doesn't fix the issue, that the protocol needs to be determined - see the unit tests for the output of this method:

https://github.com/nextcloud/server/blob/f6cd5200a20f7adfe3b3f7b48d0ade4a75829a31/tests/lib/Federation/CloudIdManagerTest.php#L36-L44

**Comment by MorrisJobke** [comment]
cc @icewind1991 to verify my cloud ID analysis

**Comment by schiessle** [comment]
makes sense 👍

**Pull request merged**
