### PR TITLE
Implement count users

### PR DESCRIPTION
**Pull request by schiessle**
implement count users to show the right number of users in the user management.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@schiessle Please always add a milestone. This makes a looking at this PR in some months a lot easier since you know when it was shipped.

**Comment by schiessle** [comment]
@MorrisJobke The app is released independent from the server so server milestones doesn't really make sense here.

**Comment by MorrisJobke** [comment]
> @MorrisJobke The app is released independent from the server so server milestones doesn't really make sense here.

Then make milestone for the versions of the app. A need to looking which commit was added when and is included in which tag makes it super horrible later to check if something is in or not.

**Comment by MorrisJobke** [comment]
I also removed it from the milestone updater script ;)

**Pull request merged**
